name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name mongo-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MongoDB to Initialize
      run: sleep 20s

    - name: Print MongoDB Logs
      run: docker logs mongo-test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        environment: NODE_ENV=test
        MONGODB_URI: mongodb://localhost:27017/testDB

    - name: Build and test
      run: |
        docker build -f Dockerfile.test -t user-alchemy-test .
        docker run -e MONGODB_URI=$MONGODB_URI user-alchemy-test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      run: heroku container:login

    - name: Build and push Docker image to Heroku
      run: |
        heroku container:push web -a user-alchemy
        heroku container:release web -a user-alchemy
