name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f Dockerfile.test -t todo-wand-api-test .

    - name: Run tests
      run: docker run todo-wand-api-test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    env:
      HEROKU_APP_NAME: todo-wand-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build and push Docker image to Heroku
      run: |
        heroku container:push web -a ${{ env.HEROKU_APP_NAME }}
        heroku container:release web -a ${{ env.HEROKU_APP_NAME }}
